services:
  users-db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data

  users-service:
    build: ./users-service
    env_file:
      - .env
    ports:
      - "${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}"
    depends_on:
      - users-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVICE_PORT: ${USERS_SERVICE_PORT}
      ACCESS_SECRET_KEY: ${ACCESS_SECRET_KEY}
      REFRESH_SECRET_KEY: ${REFRESH_SECRET_KEY}

  gateway:
    build: ./gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - users-service
    env_file:
      - .env
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      USERS_SERVICE_URL: ${USERS_SERVICE_URL}
      ACCESS_SECRET_KEY: ${ACCESS_SECRET_KEY}
      REFRESH_SECRET_KEY: ${REFRESH_SECRET_KEY}

volumes:
  users-db-data: